name: 07-expressions
on: 
    workflow_dispatch:
        inputs:
            debug:
                description: enable debug
                type: boolean
                required: true
                default: false

    push:
jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[debug] Print start-up data"
              if: ${{ inputs.debug }}
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Branch name: ${{ github.ref_name }}"
                echo "SHA: ${{ github.sha }}"
                echo "OS: ${{ runner.os }}"
            - name: "[debug] Print when triggered from main"
              if: ${{ inputs.debug }}
              run: |
                echo "I was triggered from main"
            - name: Greeting
              run: |
                echo "Hello, World"


